name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Gradle
        uses: gradle/wrapper-action@v2
        with:
          gradle-version: 7.2 # Specify the desired Gradle version here

      - name: Build with Gradle
        run: ./gradlew build
